### ISSUE TITLE
add support for Hunyuandit v1.2

### ISSUE THREAD

**Issue by sunnyyangyangyang** [DenOfEquity/Hunyuan-DiT-for-webUI#3]

**Comment by DenOfEquity** [comment]
Soon.
v1.2 needs some updates in *diffusers* to work. The changes are in the source, but not in a release yet. Hopefully soon, along with controlnet, which is also in the source.
I've hacked both sets of changes into my local install, it all works. So, just waiting on the update. <sub>assuming nothing breaks</sub>

**Comment by DenOfEquity** [comment]
Well, that took longer than expected. Updated, diffusers 0.30.0 required.
